### ISSUE TITLE
[BUG, SF plugin] The name & description are only used during create

### ISSUE THREAD

**Issue by codatoz** [raito-io/cli-plugin-snowflake#48]
When access providers are pushed info Snowflake, we use the name and description to create a comment on the newly created role. We don't update it when updating the roles though.

**Comment by michaeltandecki** [comment]
Same/similar as https://github.com/raito-io/global/issues/161? 

There I noticed we just don't ingest the "comment" field (Jerome was asking we don't have descriptions).

**Comment by rosierswannes** [comment]
Seems indeed a duplicate, can I close this one?

**Comment by codatoz** [comment]
Not a duplicate. This is about setting the comment when we create roles in Snowflake. #161 is about the other way around (snowflake roles -> Raito)

**Comment by codatoz** [comment]
Can be easily implement with https://docs.snowflake.com/en/sql-reference/sql/comment.html
